import { WeenieType } from "./mappings";
import type { StringIndexedDict } from "./types";

export const weenieTypeURLMapThing: StringIndexedDict<string> = {
  [WeenieType.Generic]: "items",
  [WeenieType.Clothing]: "items/armor",
  [WeenieType.MissileLauncher]: "items/weapons",
  [WeenieType.Missile]: "items/weapons",
  [WeenieType.Ammunition]: "items/weapons",
  [WeenieType.MeleeWeapon]: "items/weapons",
  [WeenieType.Portal]: "items/portals",
  [WeenieType.Book]: "items/books",
  [WeenieType.Coin]: "items",
  [WeenieType.Creature]: "npcs/creatures",
  [WeenieType.Admin]: "npcs/creatures",
  [WeenieType.Vendor]: "npcs/vendors",
  [WeenieType.HotSpot]: "items",
  [WeenieType.Corpse]: "items",
  [WeenieType.Cow]: "npcs/creatures",
  [WeenieType.AI]: "items",
  [WeenieType.Machine]: "items",
  [WeenieType.Food]: "items/food",
  [WeenieType.Door]: "items",
  [WeenieType.Chest]: "items",
  [WeenieType.Container]: "items",
  [WeenieType.Key]: "items",
  [WeenieType.Lockpick]: "items",
  [WeenieType.PressurePlate]: "items",
  [WeenieType.LifeStone]: "items",
  [WeenieType.Switch]: "items",
  [WeenieType.PKModifier]: "items",
  [WeenieType.Healer]: "items",
  [WeenieType.LightSource]: "items",
  [WeenieType.Allegiance]: "items",
  [WeenieType.SpellComponent]: "items",
  [WeenieType.ProjectileSpell]: "items",
  [WeenieType.Scroll]: "items",
  [WeenieType.Caster]: "items",
  [WeenieType.Channel]: "items",
  [WeenieType.ManaStone]: "items",
  [WeenieType.Gem]: "items",
  [WeenieType.AdvocateFane]: "items",
  [WeenieType.AdvocateItem]: "items",
  [WeenieType.Sentinel]: "items",
  [WeenieType.GSpellEconomy]: "items",
  [WeenieType.LSpellEconomy]: "items",
  [WeenieType.CraftTool]: "items",
  [WeenieType.LScoreKeeper]: "items",
  [WeenieType.GScoreKeeper]: "items",
  [WeenieType.GScoreGatherer]: "items",
  [WeenieType.ScoreBook]: "items",
  [WeenieType.EventCoordinator]: "items",
  [WeenieType.Entity]: "items",
  [WeenieType.Stackable]: "items",
  [WeenieType.HUD]: "items",
  [WeenieType.House]: "items",
  [WeenieType.Deed]: "items",
  [WeenieType.SlumLord]: "items",
  [WeenieType.Hook]: "items",
  [WeenieType.Storage]: "items",
  [WeenieType.BootSpot]: "items",
  [WeenieType.HousePortal]: "items",
  [WeenieType.Game]: "items",
  [WeenieType.GamePiece]: "items",
  [WeenieType.SkillAlterationDevice]: "items",
  [WeenieType.AttributeTransferDevice]: "items",
  [WeenieType.Hooker]: "items",
  [WeenieType.AllegianceBindstone]: "items",
  [WeenieType.InGameStatKeeper]: "items",
  [WeenieType.AugmentationDevice]: "items",
  [WeenieType.SocialManager]: "items",
  [WeenieType.Pet]: "items",
  [WeenieType.PetDevice]: "items",
  [WeenieType.CombatPet]: "items",
};

enum SearchResultCategory {
  Item = "item",
  Character = "character",
  World = "world",
  Other = "other",
}

export const SearchResultCategoryLabel: StringIndexedDict<string> = {
  [SearchResultCategory.Item]: "Item",
  [SearchResultCategory.Character]: "Character",
  [SearchResultCategory.World]: "World",
  [SearchResultCategory.Other]: "Other",
};

// TODO: Many of these are wrong and I need help categorizing
export const weenieTypeToSearchResultCategory: StringIndexedDict<string> = {
  [WeenieType.Generic]: SearchResultCategory.Item,
  [WeenieType.Clothing]: SearchResultCategory.Item,
  [WeenieType.MissileLauncher]: SearchResultCategory.Item,
  [WeenieType.Missile]: SearchResultCategory.Item,
  [WeenieType.Ammunition]: SearchResultCategory.Item,
  [WeenieType.MeleeWeapon]: SearchResultCategory.Item,
  [WeenieType.Portal]: SearchResultCategory.World,
  [WeenieType.Book]: SearchResultCategory.Item,
  [WeenieType.Coin]: SearchResultCategory.Other,
  [WeenieType.Creature]: SearchResultCategory.World,
  [WeenieType.Admin]: SearchResultCategory.World,
  [WeenieType.Vendor]: SearchResultCategory.World,
  [WeenieType.HotSpot]: SearchResultCategory.World,
  [WeenieType.Corpse]: SearchResultCategory.World,
  [WeenieType.Cow]: SearchResultCategory.World,
  [WeenieType.AI]: SearchResultCategory.Item,
  [WeenieType.Machine]: SearchResultCategory.Item,
  [WeenieType.Food]: SearchResultCategory.Item,
  [WeenieType.Door]: SearchResultCategory.World,
  [WeenieType.Chest]: SearchResultCategory.World,
  [WeenieType.Container]: SearchResultCategory.Item,
  [WeenieType.Key]: SearchResultCategory.Item,
  [WeenieType.Lockpick]: SearchResultCategory.Item,
  [WeenieType.PressurePlate]: SearchResultCategory.World,
  [WeenieType.LifeStone]: SearchResultCategory.World,
  [WeenieType.Switch]: SearchResultCategory.World,
  [WeenieType.PKModifier]: SearchResultCategory.World,
  [WeenieType.Healer]: SearchResultCategory.Item,
  [WeenieType.LightSource]: SearchResultCategory.World,
  [WeenieType.Allegiance]: SearchResultCategory.World,
  [WeenieType.SpellComponent]: SearchResultCategory.Item,
  [WeenieType.ProjectileSpell]: SearchResultCategory.Item,
  [WeenieType.Scroll]: SearchResultCategory.Item,
  [WeenieType.Caster]: SearchResultCategory.Item,
  [WeenieType.Channel]: SearchResultCategory.World,
  [WeenieType.ManaStone]: SearchResultCategory.Item,
  [WeenieType.Gem]: SearchResultCategory.Item,
  [WeenieType.AdvocateFane]: SearchResultCategory.Item,
  [WeenieType.AdvocateItem]: SearchResultCategory.Item,
  [WeenieType.Sentinel]: SearchResultCategory.Item,
  [WeenieType.GSpellEconomy]: SearchResultCategory.Item,
  [WeenieType.LSpellEconomy]: SearchResultCategory.Item,
  [WeenieType.CraftTool]: SearchResultCategory.Item,
  [WeenieType.LScoreKeeper]: SearchResultCategory.Item,
  [WeenieType.GScoreKeeper]: SearchResultCategory.Item,
  [WeenieType.GScoreGatherer]: SearchResultCategory.Item,
  [WeenieType.ScoreBook]: SearchResultCategory.Item,
  [WeenieType.EventCoordinator]: SearchResultCategory.Item,
  [WeenieType.Entity]: SearchResultCategory.World,
  [WeenieType.Stackable]: SearchResultCategory.Item,
  [WeenieType.HUD]: SearchResultCategory.Item,
  [WeenieType.House]: SearchResultCategory.World,
  [WeenieType.Deed]: SearchResultCategory.Item,
  [WeenieType.SlumLord]: SearchResultCategory.Item,
  [WeenieType.Hook]: SearchResultCategory.World,
  [WeenieType.Storage]: SearchResultCategory.World,
  [WeenieType.BootSpot]: SearchResultCategory.World,
  [WeenieType.HousePortal]: SearchResultCategory.World,
  [WeenieType.Game]: SearchResultCategory.Item,
  [WeenieType.GamePiece]: SearchResultCategory.Item,
  [WeenieType.SkillAlterationDevice]: SearchResultCategory.Item,
  [WeenieType.AttributeTransferDevice]: SearchResultCategory.Item,
  [WeenieType.Hooker]: SearchResultCategory.World,
  [WeenieType.AllegianceBindstone]: SearchResultCategory.World,
  [WeenieType.InGameStatKeeper]: SearchResultCategory.Item,
  [WeenieType.AugmentationDevice]: SearchResultCategory.Item,
  [WeenieType.SocialManager]: SearchResultCategory.Item,
  [WeenieType.Pet]: SearchResultCategory.World,
  [WeenieType.PetDevice]: SearchResultCategory.World,
  [WeenieType.CombatPet]: SearchResultCategory.World,
};

enum SearchResultSubCategory {
  Item = "item",
  Creature = "creature",
  Armor = "armor",
  Weapon = "weapon",
  Portal = "portal",
  Book = "book",
  Other = "other",
}

export const SearchResultSubCategoryLabel: StringIndexedDict<string> = {
  [SearchResultSubCategory.Item]: "Item",
  [SearchResultSubCategory.Creature]: "Creature",
  [SearchResultSubCategory.Armor]: "Armor",
  [SearchResultSubCategory.Weapon]: "Weapon",
  [SearchResultSubCategory.Portal]: "Portal",
  [SearchResultSubCategory.Book]: "Book",
  [SearchResultSubCategory.Other]: "Other",
};

export const SearchResultSubCategoryIcon: StringIndexedDict<string> = {
  [SearchResultSubCategory.Item]: "🛍️",
  [SearchResultSubCategory.Creature]: "👺",
  [SearchResultSubCategory.Armor]: "🛡️",
  [SearchResultSubCategory.Weapon]: "🔪",
  [SearchResultSubCategory.Portal]: "🇵🇹",
  [SearchResultSubCategory.Book]: "📚",
  [SearchResultSubCategory.Other]: "🤔",
};

export const weenieTypeToSearchResultSubCategory: StringIndexedDict<string> = {
  [WeenieType.Generic]: SearchResultSubCategory.Item,
  [WeenieType.Clothing]: SearchResultSubCategory.Armor,
  [WeenieType.MissileLauncher]: SearchResultSubCategory.Weapon,
  [WeenieType.Missile]: SearchResultSubCategory.Weapon,
  [WeenieType.Ammunition]: SearchResultSubCategory.Weapon,
  [WeenieType.MeleeWeapon]: SearchResultSubCategory.Weapon,
  [WeenieType.Portal]: SearchResultSubCategory.Portal,
  [WeenieType.Book]: SearchResultSubCategory.Book,
  [WeenieType.Coin]: SearchResultSubCategory.Item,
  [WeenieType.Creature]: SearchResultSubCategory.Creature,
  [WeenieType.Admin]: SearchResultSubCategory.Creature,
  [WeenieType.Vendor]: SearchResultSubCategory.Creature,
  [WeenieType.HotSpot]: SearchResultSubCategory.Other,
  [WeenieType.Corpse]: SearchResultSubCategory.Other,
  [WeenieType.Cow]: SearchResultSubCategory.Creature,
  [WeenieType.AI]: SearchResultSubCategory.Creature,
  [WeenieType.Machine]: SearchResultSubCategory.Other,
  [WeenieType.Food]: SearchResultSubCategory.Item,
  [WeenieType.Door]: SearchResultSubCategory.Other,
  [WeenieType.Chest]: SearchResultSubCategory.Other,
  [WeenieType.Container]: SearchResultSubCategory.Other,
  [WeenieType.Key]: SearchResultSubCategory.Item,
  [WeenieType.Lockpick]: SearchResultSubCategory.Item,
  [WeenieType.PressurePlate]: SearchResultSubCategory.Other,
  [WeenieType.LifeStone]: SearchResultSubCategory.Other,
  [WeenieType.Switch]: SearchResultSubCategory.Other,
  [WeenieType.PKModifier]: SearchResultSubCategory.Other,
  [WeenieType.Healer]: SearchResultSubCategory.Item,
  [WeenieType.LightSource]: SearchResultSubCategory.Other,
  [WeenieType.Allegiance]: SearchResultSubCategory.Other,
  [WeenieType.SpellComponent]: SearchResultSubCategory.Item,
  [WeenieType.ProjectileSpell]: SearchResultSubCategory.Other,
  [WeenieType.Scroll]: SearchResultSubCategory.Item,
  [WeenieType.Caster]: SearchResultSubCategory.Weapon,
  [WeenieType.Channel]: SearchResultSubCategory.Other,
  [WeenieType.ManaStone]: SearchResultSubCategory.Item,
  [WeenieType.Gem]: SearchResultSubCategory.Item,
  [WeenieType.AdvocateFane]: SearchResultSubCategory.Other,
  [WeenieType.AdvocateItem]: SearchResultSubCategory.Other,
  [WeenieType.Sentinel]: SearchResultSubCategory.Other,
  [WeenieType.GSpellEconomy]: SearchResultSubCategory.Other,
  [WeenieType.LSpellEconomy]: SearchResultSubCategory.Other,
  [WeenieType.CraftTool]: SearchResultSubCategory.Item,
  [WeenieType.LScoreKeeper]: SearchResultSubCategory.Other,
  [WeenieType.GScoreKeeper]: SearchResultSubCategory.Other,
  [WeenieType.GScoreGatherer]: SearchResultSubCategory.Other,
  [WeenieType.ScoreBook]: SearchResultSubCategory.Other,
  [WeenieType.EventCoordinator]: SearchResultSubCategory.Other,
  [WeenieType.Entity]: SearchResultSubCategory.Other,
  [WeenieType.Stackable]: SearchResultSubCategory.Other,
  [WeenieType.HUD]: SearchResultSubCategory.Other,
  [WeenieType.House]: SearchResultSubCategory.Other,
  [WeenieType.Deed]: SearchResultSubCategory.Other,
  [WeenieType.SlumLord]: SearchResultSubCategory.Other,
  [WeenieType.Hook]: SearchResultSubCategory.Other,
  [WeenieType.Storage]: SearchResultSubCategory.Other,
  [WeenieType.BootSpot]: SearchResultSubCategory.Other,
  [WeenieType.HousePortal]: SearchResultSubCategory.Other,
  [WeenieType.Game]: SearchResultSubCategory.Other,
  [WeenieType.GamePiece]: SearchResultSubCategory.Other,
  [WeenieType.SkillAlterationDevice]: SearchResultSubCategory.Other,
  [WeenieType.AttributeTransferDevice]: SearchResultSubCategory.Other,
  [WeenieType.Hooker]: SearchResultSubCategory.Other,
  [WeenieType.AllegianceBindstone]: SearchResultSubCategory.Other,
  [WeenieType.InGameStatKeeper]: SearchResultSubCategory.Other,
  [WeenieType.AugmentationDevice]: SearchResultSubCategory.Other,
  [WeenieType.SocialManager]: SearchResultSubCategory.Other,
  [WeenieType.Pet]: SearchResultSubCategory.Creature,
  [WeenieType.PetDevice]: SearchResultSubCategory.Item,
  [WeenieType.CombatPet]: SearchResultSubCategory.Creature,
};
